spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://192.168.144.1:5432/expedia-platform-db"
      driver-class-name: org.postgresql.Driver
      username: expedia
      password: 1234
  sql:
    init:
      mode: always
      schema-locations: classpath:common/member/schema.sql
      data-locations: classpath:common/member/data.sql.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true