
spring.banner.location: common/banner.txt

spring:
  profiles:
    group:
      local:
        - common
        - local
      test:
        - common
        - test
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: common

security:
  jwt:
    token:
      secret-key: expedia-secret-key
      access-token-expire-length: 3600
      refresh-token-expire-length: 360000
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: validate
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: validate
