# docker compose -f docker-compose.yml up -d --build
# docker compose -f docker-compose.yml build --no-cache
# redis-cli: docker exec -it {containerId} redis-cli
   # keys *
   # get key {keyName}
version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: expedia-redis
    networks:
      - internal-network
    ports:
      - "6379:6379"
    command: redis-server
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1234
    networks:
      - internal-network
  membrer-server:
    container_name: expedia-member
    build: ../member-server
    ports:
      - "8081:8081"
    networks:
      - internal-network
  auth-server:
    container_name: expedia-auth
    build: ../auth-server
    ports:
      - "8082:8082"
    depends_on:
      - redis
    networks:
      - internal-network
networks:
  internal-network:
    driver: bridge