
spring.banner.location: common/banner.txt

spring:
  profiles:
    group:
      local:
        - common
        - local
      test:
        - common
        - test
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: common

security:
  jwt:
    token:
      secret-key: expedia-secret-key
      expire-length: 3600000
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/expedia_authentication
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: validate
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: 'jdbc:h2:mem:authentication'
    username: 'user'
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: validate
