spring:
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/expediadb
    username: expedia
    password: 1234
    driver-class-name: org.postgresql.Driver
  # init data
  sql:
    init:
      mode: always
      schema-locations: classpath:accommodation/schema/*.sql
      data-locations: classpath:accommodation/data/*.sql

  # JPA
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
